### ISSUE TITLE
Finish box3

### ISSUE THREAD

**Issue by amlalejini** [stateSpaceRobotics/learn_ros_sandbox#1]
Box three has some stated goals in the comments that have not actually been completed.  Someone should do this at some point.

**Comment by bgrayd** [comment]
I have implemented it.  Do you think it would be more useful to wait to push it and see if one of the new people can do it, or is it more helpful to let them see it?

**Comment by amlalejini** [comment]
This is a place for people to see examples of things (and submit examples if they make them), so I would recommend pushing it.

**Comment by bgrayd** [comment]
Submitted
